release-date = "2022-03-17"

[[entries]]
id = "17d2c8db-4dd2-452d-86ec-4e34ff7493b9"
type = "fix"
description = "Fix an error caused when using `Type.get_orig_bases()` if the `Type.type` has non-generic bases"
author = "@NiklasRosenstein"

[[entries]]
id = "6e9ebd6e-1e63-4840-805e-6f501ab05b2a"
type = "deprecation"
description = "Deprecated `get_type_hints()` in favor of new `get_annotations()`"
author = "@NiklasRosenstein"

[[entries]]
id = "e1123609-d7eb-4f2d-87f7-e4c518c92b99"
type = "fix"
description = "Fix `get_annotations()` in Python 3.9 and older to have the same behaviour as `inspect.get_annotations()` in that it does not include annotations of a classes' bases"
author = "@NiklasRosenstein"

[[entries]]
id = "6d7fa3d0-433c-4240-a49f-9b617d0a2184"
type = "feature"
description = "Add `typeapi.utils.is_typed_dict()` and the `typeapi.utils.TypedDict` protocol"
author = "@NiklasRosenstein"
