release-date = "2022-03-22"

[[entries]]
id = "7a8be2d2-f835-4373-ae29-eb522e41fddf"
type = "improvement"
description = "add `get_annotations(include_bases)` parameter"
author = "@NiklasRosenstein"

[[entries]]
id = "eeec2850-4a3c-466b-b481-80ebf0705283"
type = "improvement"
description = "update `ForweardRef.__repr__()`"
author = "@NiklasRosenstein"
