release-date = "2023-03-23"

[[entries]]
id = "f0ffe76e-8711-40c2-9ecd-c58a1809dd76"
type = "docs"
description = "Clarify that future type hint evaluation for Union-style syntax continues to return a `typing.Union` instead of `types.UnionType` even in Python 3.10+."
author = "@NiklasRosenstein"

[[entries]]
id = "2c0d1cad-f130-408a-aa13-1cf7f899c594"
type = "fix"
description = "Fix taking into account an objects origin module for the global namespace when resolving forward references."
author = "@NiklasRosenstein"
