release-date = "2023-06-11"

[[entries]]
id = "641cd28b-3814-4b62-8bd1-c6b88fc71d5a"
type = "improvement"
description = "`TupleTypeHint` is now a subclass of `ClassTypeHint`; `ClassTypeHint.bases` no longer returns none"
author = "@NiklasRosenstein"
