release-date = "2023-06-12"

[[entries]]
id = "a644d3b9-b9f7-4c9c-b240-2be2599e70d5"
type = "breaking change"
description = "A plain `tuple` type is no longer represented by a `TupleTypeHint`, but instead by a `ClassTypeHint`."
author = "@NiklasRosenstein"
