[[entries]]
id = "a5578e7f-32ca-442e-b52a-e6a16c573c35"
type = "fix"
description = "`ClassTypeHint.bases` now falls back to the types actual base classes if it is not a generic type"
author = "@NiklasRosenstein"
