[[entries]]
id = "0922059c-e19b-4743-8e29-3240ecfaa82b"
type = "breaking change"
description = "Change `ForwardRef` and `NewType` to hold the origin `typing` object"
author = "@NiklasRosenstein"

[[entries]]
id = "eab7b8bd-7805-4b33-8dae-ba17dd3cdb0b"
type = "feature"
description = "Implement `ForwardRef.evaluate()`"
author = "@NiklasRosenstein"
