[[entries]]
id = "e7afde99-2c2d-493a-bb4e-120d56e41a36"
type = "fix"
description = "Fixed an error when evaluating `FakeHint` objects when an argument to a type-hint such as `Annotated` was the constant value `True`, `False`, `None`, `0` or `1`."
author = "@NiklasRosenstein"
