[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
classifiers = []
dependencies = ["typing-extensions>=3.0.0"]
description = ""
keywords = []
license = "MIT"
name = "typeapi"
readme = "README.md"
requires-python = ">=3.8"
version = "2.2.4"

[[project.authors]]
mail = "rosensteinniklas@gmail.com"
name = "Niklas Rosenstein"

[[project.packages]]
from = "src"
include = "typeapi"

[project.urls]
"Bug Tracker" = "https://github.com/NiklasRosenstein/python-typeapi/issues"
Documentation = "https://niklasrosenstein.github.io/python-typeapi/"
Homepage = "https://github.com/NiklasRosenstein/python-typeapi"

[tool.mypy]
enable_error_code = "ignore-without-code, possibly-undefined"
explicit_package_bases = true
mypy_path = ["src"]
namespace_packages = true
pretty = false
python_version = "${TIRE_MIN_PYTHON_VERSION}"
show_error_codes = true
show_error_context = true
strict = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "--ignore=docs/mksync-hook.py --ignore=scripts/dump_type_vars.py"
console_output_style = "count"
log_cli_level = "info"
verbosity_assertions = 2
verbosity_test_cases = 1

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.lint.isort]
forced-separate = ["test", "tests", "testing", "testsuite"]

[tool.uv]
dev-dependencies = ["astor>=0.8.1,<1.0.0", "mypy>=1.14.1", "pytest>=8.3.4", "ruff>=0.9.3", "types-dataclasses>=0.6.5,<1.0.0"]
