site_name: Python Typeapi
repo_name: GitHub
repo_url: https://github.com/NiklasRosenstein/python-typeapi
edit_uri: edit/develop/docs/content/
theme: readthedocs
markdown_extensions:
  - footnotes
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
