site_name: python-typeapi
repo_url: https://github.com/NiklasRosenstein/python-typeapi
repo_name: NiklasRosenstein/python-typeapi
theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
    accent: deep orange
  features:
    - navigation.sections
hooks:
  - mksync-hook.py
watch:
  - ../src
  - mksync-hook.py

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../src]
          options:
            heading_level: 3
            show_root_heading: true
            show_root_full_path: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            separate_signature: true
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - features.md
  - examples.md
  - API:
    - typeapi: api/typeapi.md
  - Other:
    - Changelog: changelog.md
