name: Documentation

on:
  push:
    branches: [ "develop" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: NiklasRosenstein/slap@gha/install/v1
    - run: slap install --only-extras docs --no-venv-check
    - run: slap run --no-venv-check docs:build
    - uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/_site

  docs-publish:
    needs: [ docs ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with: { name: docs, path: docs/site }
    - uses: JamesIves/github-pages-deploy-action@v4.5.0
      with: { branch: gh-pages, folder: docs/site, ssh-key: "${{ secrets.DEPLOY_KEY }}" }
